name: release

on:
  push:
    tags:
      - v*.*.*

permissions: read-all

env:
  tag: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      os: linux
      arch: x86_64
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | 1567,v4.2.2
      - name: Get release version
        id: releaseVersion
        shell: bash
        run:
          echo "releaseVersion=\"$(awk -F\' '/const releaseVersion/ { print $2
          }' src/version.js)\"" >> "$GITHUB_ENV"
      - name: Check if releaseVersion is same as tag
        run: |
          if [ "${{ env.tag }}" != "${{ env.releaseVersion }}" ]; then
            echo "releaseVersion does not match the tag"
            exit 1
          fi
      - name: Fetch MITM-Proxy
        shell: bash
        run: |
          mkdir -p mitmproxy
          wget https://github.com/rohitcoder/go-libaudit/releases/download/v2.6.1/auparse-v2.6.1-linux-amd64 --quiet
          wget https://downloads.mitmproxy.org/10.2.2/mitmproxy-10.2.2-${{ env.os }}-${{ env.arch }}.tar.gz --quiet
          tar -xzf mitmproxy-10.2.2-${{ env.os }}-${{ env.arch }}.tar.gz -C mitmproxy
          mkdir -p hardener
          cp mitmproxy/mitmdump hardener/mitmdump
          cp src/intercept.py hardener/intercept.py
          cp auparse-v2.6.1-linux-amd64 hardener/auparse
          tar -czf hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz hardener
          rm -rf mitmproxy hardener
          rm mitmproxy-10.2.2-linux-x86_64.tar.gz
      - name: Install Cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # sigstore/cosign-installer@v3.8.1
        with:
          cosign-release: 'v2.2.4' # optional
      - name: Sign Release
        shell: bash
        run: |
          cosign sign-blob \
            --yes \
            --bundle hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.bundle \
            --output-signature hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.sig \
            --output-certificate hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.cert \
            hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz

      - name: Generate hashes
        shell: bash
        id: hash
        run: |
          # sha256sum generates sha256 hash for all artifacts.
          # base64 -w0 encodes to base64 and outputs on a single line.
          # sha256sum artifact1 artifact2 ... | base64 -w0
          echo "hashes=$(sha256sum hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz \
            hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.bundle \
            hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.sig \
            hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.cert | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Upload tarball
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # actions/upload-artifact@v4 | main,v4.6.1
        with:
          name: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz
          path: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz
          if-no-files-found: error
          retention-days: 5

      - name: Upload signature
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # actions/upload-artifact@v4 | main,v4.6.1
        with:
          name: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.sig
          path: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.sig
          if-no-files-found: error
          retention-days: 5

      - name: Upload certificate
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # actions/upload-artifact@v4 | main,v4.6.1
        with:
          name: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.cert
          path: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.cert
          if-no-files-found: error
          retention-days: 5

      - name: Upload verification bundle
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # actions/upload-artifact@v4 | main,v4.6.1
        with:
          name: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.bundle
          path: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.bundle
          if-no-files-found: error
          retention-days: 5

  provenance:
    needs: [build]
    if:
      ${{ !endsWith(github.ref_name, 'rc') && !contains(github.ref_name, 'rc.')
      }}
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: '${{ needs.build.outputs.hashes }}'
      upload-assets: true

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      os: linux
      arch: x86_64
    steps:
      - name: Download tarball
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # actions/download-artifact@v4 | main,209,v4.1.9
        with:
          name: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz

      - name: Download signature
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # actions/download-artifact@v4 | main,209,v4.1.9
        with:
          name: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.sig

      - name: Download certificate
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # actions/download-artifact@v4 | main,209,v4.1.9
        with:
          name: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.cert

      - name: Download bundle
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # actions/download-artifact@v4 | main,209,v4.1.9
        with:
          name: hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.bundle

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # sigstore/cosign-installer@v3.8.1
        with:
          cosign-release: 'v2.2.4' # optional

      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # softprops/action-gh-release@v2
        with:
          files: |
            hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz
            hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.bundle
            hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.sig
            hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.cert
          tag_name: ${{ env.tag }}
          name: ${{ env.tag }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ endsWith(env.tag, 'rc') || contains(env.tag, 'rc.') }}

      - name: Verify Release
        run: |
          cosign verify-blob \
            --bundle hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz.bundle \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/release.yml@refs/tags/${{ env.tag }}" \
            hardener-${{ env.tag }}-${{ env.os }}-${{ env.arch }}.tar.gz
